### ISSUE TITLE
Is it normal for my Charachorder device to come with almost 400 non-displayable chords? May I delete them? How?

### ISSUE THREAD

**Issue by rayluo** [GetPsyched/charachorder.py#4]
Hi @GetPsyched and @Raymo111 , thanks for providing a Python library for Charachorder devices! This opens door to unlimited possibilities!

I got my hands on a new-ish Charachorder Lite M0 device today, which I just upgraded the firmware to the latest 1.1.4. I can add new chord(s) into it and they worked. But I also noticed that there are nearly 400 pre-existing chords in the device that contains no phase at all. Are they some useless relic? Can they be safely deleted without affecting all the built-in "hot keys" such as "RightAlt + G" or "RightAlt + I"?

```
('n', 'p') ('p', 'y', 't', 'h', 'o', 'n')
('Ȁ', 'ŀ', '\x90', 'Ƥ', 'm', 'Ϝ', '̦', 'Ǒ') ()
('̀', '\x80', 'ǌ', '\x90', 'Ƥ', 'm', 'Ϝ', '̦', 'Ǒ') ()
('Ġ', 'Ā', '\x02', '\x80', 'ǌ', 'ɥ', 'ě', 'ɗ', 'ƹ') ()
...
```

I believe I attempted to delete them all via Device Manager but it did not seem to work. Was that because those 400 chords are built-in and read-only, or was it simply some adhoc error?

Ultimately, I want to build some scripts for me to programmatically add and maintain my chords.

**Comment by Raymo111** [comment]
The 400 chords number looks like the starter chords that are added after a factory reset. Can you back up the chords, factory reset, and see if they're fixed?

**Comment by rayluo** [comment]
Those 400 chords were definitely messed up because my export (quoted above) were in incorrect format (visible by comparing to the "python" chord that I created).

But, thanks for your hint and this library, I have been able to delete them all, and re-append a new set of starter chords.

**Comment by Raymo111** [comment]
> Those 400 chords were definitely messed up because my export (quoted above) were in incorrect format (visible by comparing to the "python" chord that I created).
> 
> But, thanks for your hint and this library, I have been able to delete them all, and re-append a new set of starter chords.

Awesome, glad to hear it!
